### ISSUE TITLE
Github Action not working

### ISSUE THREAD

**Issue by elliottminns** [SmartBear/swaggerhub-cli#254]
### Q&A (please complete the following information)
 - CLI version: [e.g. 1.0.0] 0.6.1
 - OS: [e.g. macOS Catalina] Ubuntu
 - Node.js version: [e.g. 12.16.3] 10
 - SwaggerHub version if On-Premise: [e.g. 1.24.0-52]

### To reproduce...
1. Given the example github action, run it in the pipeline as:
```yaml
  swaggerhub:
    name: Update swaggerhub
    runs-on: ubuntu-latest
    env:
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
      SWAGGERHUB_URL: https://api.swaggerhub.com
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish API service OAS
        uses: smartbear/swaggerhub-cli@v0.6.1
        continue-on-error: false
        with:
          args: api:update my-apis/my_api -f my-api-spec.yaml
```

2. Push up the action
3. Error when running the pipeline action in Github

```
(node:10) [EACCES] Error Plugin: swaggerhub-cli: EACCES: permission denied, mkdir '/github/home/.config/swaggerhub-cli'
module: @oclif/config@1.18.2
task: runHook init
plugin: swaggerhub-cli
root: /cli
See more details with DEBUG=*
    Error: /github/home/.config/swaggerhub-cli/config.json: ENOENT: no such 
    file or directory, open '/github/home/.config/swaggerhub-cli/config.json'
    Code: ENOENT
```

### Expected behavior

Workaround has been to use 

```
uses: smartbear/swaggerhub-cli@3ee9d3ea4539a3db6c408afc55dbca308f804148
```

Which appears to be a working commit
